// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwDnPhE6cDqNs4sZJdcsoJ4JE6WeV_5BI',
    appId: '1:285342174001:web:91cbce6cc8e0d72a757e10',
    messagingSenderId: '285342174001',
    projectId: 'smallapps-da23c',
    authDomain: 'smallapps-da23c.firebaseapp.com',
    storageBucket: 'smallapps-da23c.appspot.com',
    measurementId: 'G-HCZKZGPYXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwTT2NK9G0JnuXjehf66caY0MC16gRxrs',
    appId: '1:285342174001:android:e62b9689b4b09828757e10',
    messagingSenderId: '285342174001',
    projectId: 'smallapps-da23c',
    storageBucket: 'smallapps-da23c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcwo_bt5Q4uo23QK4e6nlR7nCWDYiPD00',
    appId: '1:285342174001:ios:ed958f8bfaf99f4c757e10',
    messagingSenderId: '285342174001',
    projectId: 'smallapps-da23c',
    storageBucket: 'smallapps-da23c.appspot.com',
    androidClientId: '285342174001-34rjcb0s8c25o82em6bhlha6m227rl7d.apps.googleusercontent.com',
    iosClientId: '285342174001-8cvkku8mf3n3o06kt7j0e10daletgcih.apps.googleusercontent.com',
    iosBundleId: 'com.example.landWiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcwo_bt5Q4uo23QK4e6nlR7nCWDYiPD00',
    appId: '1:285342174001:ios:bfd25865f93cbda6757e10',
    messagingSenderId: '285342174001',
    projectId: 'smallapps-da23c',
    storageBucket: 'smallapps-da23c.appspot.com',
    androidClientId: '285342174001-34rjcb0s8c25o82em6bhlha6m227rl7d.apps.googleusercontent.com',
    iosClientId: '285342174001-lus0e0bt7kfjue685s5mract1k0akq77.apps.googleusercontent.com',
    iosBundleId: 'com.example.landWiki.RunnerTests',
  );
}
